blank_issues_enabled: false
contact_links:
    - name: Questions or help
      url: https://github.com/midnights-ra1n/muses-client/discussions
      about: Ask questions or get help in the discussions section
